# Site settings
title: nattylense
description: nattylense official page
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:

# Collection settings
collections:
  photos:

# Social settings
500px_url: https://500px.com/nattylense
facebook_url:
github_url: https://github.com/ljrzarate/
gitlab_url:
googleplus_url:
instagram_url: http://instagram.com/nattylense
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
